name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: filetolink:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Run Deployment
        uses: addnab/docker-run-action@v3
        with:
          image: filetolink:latest
          envs: |
            API_ID=${{ secrets.API_ID }}
            API_HASH=${{ secrets.API_HASH }}
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          options: --restart unless-stopped
          run: |
            python3 bot.py
