name: Build & Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose down
            docker compose pull
            docker compose up -d
